name: Store version artifacts

on:
  workflow_run:
    workflows: ["MCLOUD app release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  combine-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version of server
        id: retrieve-server
        run: |
          VERSION=$(curl -s https://api.github.com/repos/nextmcloud/server/releases/latest | jq -r '.tag_name')
          echo "::set-output name=VERSION::$NC_TAG"

      - name: Get version of nmcprovisioning
        id: retrieve-nmcprovisioning
        run: |
          VERSION=$(curl -s https://api.github.com/repos/nextmcloud/nmcprovisioning/releases/latest | jq -r '.tag_name')
          echo "::set-output name=VERSION::$NMCPROVISIONING_TAG"

      - name: Get version of user_oidc
        id: retrieve-user_oidc
        run: |
          VERSION=$(curl -s https://api.github.com/repos/nextmcloud/user_oidc/releases/latest | jq -r '.tag_name')
          echo "::set-output name=VERSION::$USER_OIDC_TAG"

      - name: Get version of nmctheme
        id: retrieve-nmctheme
        run: |
          VERSION=$(curl -s https://api.github.com/repos/nextmcloud/nmctheme/releases/latest | jq -r '.tag_name')
          echo "::set-output name=NMCTHEME_TAG::$NMCTHEME_TAG"

      - name: Combine version artifacts
        run: |
          echo "customisation-${NC_TAG}" > versions-combined.txt
          echo "${NMCPROVISIONING_TAG}" >> versions-combined.txt
          echo "${USER_OIDC_TAG}" >> versions-combined.txt
          echo "${NMCTHEME_TAG}" >> versions-combined.txt

      - name: Upload combined version artifacts
        uses: actions/upload-artifact@v2
        with:
          name: versions-combined
          path: versions-combined.txt